apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/thienlh/node-docker-good-defaults:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/thienlh/node-docker-good-defaults:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: node-docker-good-defaults
        chartPath: charts/node-docker-good-defaults
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/thienlh/node-docker-good-defaults"
          image.tag: "{{.TAG}}"
